name: TourGuide CI

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master

jobs:
  build-test-package:
    runs-on: ubuntu-latest

    steps:

      # 1. Récupérer le code du repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Installer .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0.x'

      # 3. Restaurer les dépendances
      - name: Restore dependencies
        run: dotnet restore TourGuide.sln

      # 4. Compiler la solution
      - name: Build solution
        run: dotnet build TourGuide.sln --configuration Release --no-restore

      # 5. Lancer les tests
      - name: Run tests
        run: dotnet test TourGuideTest/TourGuideTest.csproj --configuration Release --no-build --logger trx --verbosity normal

      # 6. Upload des résultats de tests
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: '**/*.trx'

      # 7. Publier les artéfacts
      - name: Publish application
        run: dotnet publish TourGuide.sln --configuration Release --output publish

      # 8. Upload des artéfacts
      - name: Zip artefact
        run: zip -r TourGuide.zip publish

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: TourGuide-zip
          path: TourGuide.zip
